version: '3.8'

services:
  candidate:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"  # Map port 1433 on the host to port 1433 on the container
    environment:
      - SA_PASSWORD=Docker1Candid@te
      - ACCEPT_EULA=Y

