name: .NET Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build Candidate.Tests
      run: dotnet build Candidate.Tests/Candidate.Tests.csproj --no-restore
    - name: Build Candidate
      run: dotnet build Candidate/Candidate.csproj --no-restore
    - name: Test
      run: dotnet test Candidate.Tests/Candidate.Tests.csproj --no-build --verbosity normal
